#!/usr/bin/env bash
#Script displaying "Best School" 10 times, except on line 4 "Bad Luck" and line 8 saying "Good Luck"
j=0
while ((j < 10))
do
if [ $j -eq 3 ]
then
echo "bad luck"
elif [ $j -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
((j++))
done 
