#!/usr/bin/env bash
#Script displays information about the "School" file
FILE="School"
if [ -e $FILE ];
then
echo "School file exists"
if [ -s $FILE ];
then
echo "School file is not empty"
else
echo "School file is empty"
fi
if [ -f $FILE ];
then
echo "School is a regular file"
fi
else
echo "School file does not exist"
fi
